apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hpa-deploy
  name: hpa-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hpa-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hpa-deploy
    spec:
      containers:
      - image: dbgurum/k8s-lab:hpa
        name: k8s-lab
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
          limits:
            cpu: 20m
    