apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp-deploy
  name: webapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp-deploy
    spec:
      containers:
      - image: nginx:1.25.3-alpine
        name: webapp-deploy
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
          limits:
            cpu: 20m
