apiVersion: v1
kind: Pod
metadata:
  name: pod-vol1
spec:
  containers:
  - name: container1
    image: dbgurum/k8s-lab:initial
    volumeMounts:
    - name: empty-dir
      mountPath: /mount1
  - name: container2
    image: dbgurum/k8s-lab:initial
    volumeMounts:
    - name: empty-dir
      mountPath: /mount2
      readOnly: true
  volumes:
  - name: empty-dir
    emptyDir: {}
    