apiVersion: v1
kind: Pod
metadata:
  name: label-pod-a
  namespace: infra-team-ns2
  labels:
    type: infra2
spec:
  containers:
  - name: pod-a-container
    image: dbgurum/k8s-lab:initial

---

apiVersion: v1
kind: Pod
metadata:
  name: label-pod-b
  namespace: infra-team-ns2
  labels:
    type: infra2
spec:
  containers:
  - name: pod-b-container
    image: dbgurum/k8s-lab:initial

---

apiVersion: v1
kind: Pod
metadata:
  name: label-pod-c
  namespace: infra-team-ns2
  labels:
    type: infra2
spec:
  containers:
  - name: pod-c-container
    image: dbgurum/k8s-lab:initial

---

apiVersion: v1
kind: Service
metadata:
  name: infra-svc1
  namespace: infra-team-ns2
spec:
  selector:
    type: infra2
  ports:
  - port: 7777
