apiVersion: v1
kind: Pod
metadata:
  name: mydb-pod
  labels:
    run: db
spec:
  containers:
  - image: mysql:8.0-debian
    name: mydb
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: k8spass#

---

apiVersion: v1
kind: Service
metadata:
  name: mydb-srv
spec:
  selector:
    run: db
  ports:
  - port: 13306
    targetPort: 3306
  externalIPs:
  - 192.168.56.102