apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    key1: balue1
  name: mylabel1
spec:
  containers:
  - image: nginx:1.25.3-alpine
    name: mylqael1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
