apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
  namespace: frontend-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: ohhong/flask-front:v1.1
        name: frontend
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "app.py"
        - name: REDIS_SERVER
          value: 172.97.83.246
        command: ["sh"]
        args: ["-c", "flask run --host=0.0.0.0"]

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-public
  namespace: frontend-ns
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: frontend
