apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: backend-ns
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - image: redis:7
        name: slave
        env:
        - name: GET_HOST_FROM
          value: 172.97.83.246
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: backend-ns
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
    tier: backend

