apiVersion: v1
kind: Pod
metadata:
  name: cm-sec-pod
spec:
  containers:
  - name: cm-sec-container
    image: dbgurum/k8s-lab:initial
    envFrom:
    - configMapRef:
        name: cm-dev
    - secretRef:
        name: sec-dev