apiVersion: v1
data:
  nginx.conf: |
    events { worker_connections 1024; }

    http {
        upstream webapp {
            server localhost:9000;
        }

        server {
            listen 80;
            location / {
                proxy_pass http://webapp;
                proxy_redirect off;
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2024-04-19T00:56:14Z"
  name: flaskapp-proxy
  namespace: default
  resourceVersion: "260355"
  uid: 2ae181a9-ff66-41c8-8361-7a397b591a41
