apiVersion: v1
kind: Pod
metadata:
  name: np-pod-1
  labels:
    app: test
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node1
  containers:
  - name: c1
    image: dbgurum/k8s-lab:v1.0
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Pod
metadata:
  name: np-pod-2
  labels:
    app: test
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node2
  containers:
  - name: c1
    image: dbgurum/k8s-lab:v1.0
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Pod
metadata:
  name: np-pod-3
  labels:
    app: test
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node1
  containers:
  - name: c1
    image: dbgurum/k8s-lab:v1.0
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Pod
metadata:
  name: np-pod-4
  labels:
    app: test
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node2
  containers:
  - name: c1
    image: dbgurum/k8s-lab:v1.0
    ports:
    - containerPort: 8080

---


apiVersion: v1
kind: Service
metadata:
  name: np-pod-svc
spec:
  selector:
    app: test
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31111
  type: NodePort



