apiVersion: v1
kind: Pod
metadata:
  name: s-pod3
spec:
  nodeSelector:
    nodeName: k8s-node2
  containers:
  - image: ohhong/mynode:1.0
    name: node-container
    ports:
    - containerPort: 8080