apiVersion: v1
kind: Pod
metadata:
  name: s-pod1
spec:
  nodeSelector:
    kubernets.io/hostname: k8s-node1
  containers:
  - image: ohhong/mynode:1.0
    name: node-container
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Pod
metadata:
  name: s-pod2
spec:
  nodeSelector:
    kubernets.io/hostname: k8s-node2
  containers:
  - image: ohhong/mynode:1.0
    name: node-container
    ports:
    - containerPort: 8080
