apiVersion: v1
kind: Pod
metadata:
  name: tolerations-pod
spec:
  nodeSelector:
    gpu: nvidia
  containers:
  - image: ohhong/mynode:1.0
    name: node-container
    ports:
    - containerPort: 8080
  tolerations:
  - key: gpu
    operator: "Equal"
    value: nvidia
    effect: NoSchedule
