apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smoke-test
  name: smoke-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smoke-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: smoke-test
    spec:
      containers:
      - image: python:2.7
        name: python
        ports:
        - containerPort: 8080
        command: ["/bin/bash"]
        args: ["-c", "echo \"<h1>Hello from $(hostname)</h1>\" > index.html; python -m SimpleHTTPServer 8080"]

---

apiVersion: v1
kind: Service
metadata:
  name: smoke-svc
spec:
  selector:
    app: smoke-test
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
