#version: "3.3"
services:
 client:
   image: 'lukondefmwila/dkr-multicontainer-app-client'
   container_name: client
   ports:
     - '3000:3000'
 backend:
   image: 'lukondefmwila/dkr-multicontainer-app-backend'
   container_name: backend
   ports:
     - '3001:3001'