apiVersion: v1
kind: Pod
metadata:
  name: log-pod
spec:
  containers:
  - name: sidecar-container
    image: nginx:1.25.2
    volumeMounts:
    - name: html-log
      mountPath: /usr/share/nginx/html
  - name: runtime-container
    image: debian:10
    volumeMounts:
    - name: html-log
      mountPath: /html-log
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html-log/index.html;
          sleep 1;
        done
  volumes:
  - name: html-log
    emptyDir: {}