apiVersion: v1
kind: Pod
metadata:
  name: mynode2-pod
spec:
  containers:
  - image: ohhong/mynode:2.0
    name: node-container
    ports:
    - containerPort: 9090
    envFrom:
    - configMapRef:
        name: apikey-cm

