apiVersion: v1
kind: Pod
metadata:
  name: temp-mem-pod
spec:
  volumes:
  - name: memory-vol
    emptyDir:
      medium: Memory
      sizeLimit: 1Gi
  containers:
  - image: dbgurum/k8s-lab:initial
    name: mem-container
    volumeMounts:
    - name: memory-vol
      mountPath: /mem-mount