apiVersion: v1
kind: Pod
metadata:
  name: myblog-pod
  labels:
    app: myblog
spec:
  nodeName: k8s-node1
  containers:
  - image: ghost:4.34.3
    name: blog-container
    ports:
    - containerPort: 2368
    env:
    - name: url
      value: http://localhost:3001
    volumeMounts:
    - name: myblog
      mountPath: /var/lib/ghost/content
  volumes:
  - name: myblog
    hostPath:
      path: /home/student/content
      type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: myweb-svc
spec:
  selector:
    app: myblog
  ports:
  - port: 3001
    name: blogport
    targetPort: 2368
  externalIPs:
  - 192.168.56.101