apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod2
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node2
  containers:
  - name: mysql-container
    image: mysql:8.0-debian
    volumeMounts:
    - name: host-path
      mountPath: /var/lib/mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
  volumes:
  - name: host-path
    hostPath:
      path: /data_dir/mysql-data
      type: DirectoryOrCreate




    