apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-pvc1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "openebs-hostpath"


      