apiVersion: v1
kind: Pod
metadata:
  name: log-mode-pod
spec:
  containers:
  - image: nginx:1.25.3
    name: node-container
    volumeMounts:
    - name: cm-volume
      mountPath: /etc/config
  volumes:
  - name: cm-volume
    configMap:
      name: log-mode