apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: web-container
    image: nginx:1.25.3-alpine
    volumeMounts:
    - name: nginx-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-volume
    configMap:
      name: html-cm