apiVersion: v1
kind: Pod
metadata:
  name: redis-log-mode-pod
spec:
  containers:
  - name: redis-cm-container
    image: redis
    volumeMounts:
    - name: redis-volume
      mountPath: /opt/redis/config
  volumes:
  - name: redis-volume
    configMap:
      name: redis-config-cm