apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis-db
  name: redis-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-db
    spec:
      containers:
      - image: redis:5
        name: redis
        resources: {}
status: {}
