apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: exam7
  name: exam7
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - ls; sleep 3600;
    image: busybox
    name: exam7
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
