apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo 'Hi I am from Main Container' >> /var/log/index.html; sleep 5; done
    image: busybox
    name: busybox
    volumeMounts:
    - mountPath: /var/log
      name: cache-volume
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}

