apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - image: nginx
    name: pod1
    env:
      - name: user_name
        valueFrom:
          secretKeyRef:
            name: super-secret
            key: name

---

apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - image: nginx
    name: pod2
    envFrom:
    - secretRef:
        name: super-secret
