apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-monitoring
  labels:
    app: prometheus-monitoring
spec:
  selector:
    matchLabels:
      app: prometheus-monitoring
  template:
    metadata:
      labels:
        app: prometheus-monitoring
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: prometheus-monitoring
        image: prom/prometheus