apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-kusc00201
  labels:
    app: ds-kusc00201
spec:
  selector:
    matchLabels:
      app: ds-kusc00201
  template:
    metadata:
      labels:
        app: ds-kusc00201
    spec:
      containers:
      - name: ds-kusc00201
        image: nginx