apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - args:
    - nginx
    image: nginx
    name: pod
    ports:
    - containerPort: 80

# kr pod nginx --image=nginx --port=80