apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app_runtime_stage: dev
  name: kual00201
spec:
  replicas: 7
  selector:
    matchLabels:
      app_runtime_stage: dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        app_runtime_stage: dev
    spec:
      containers:
      - image: nginx
        name: nginx
