apiVersion: v1
kind: Pod
metadata:
  labels:
    env: pord
  name: test1
spec:
  containers:
  - image: nginx
    name: test1

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    env: dev
  name: test2
spec:
  containers:
  - image: nginx
    name: test1

