apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-kusc00401
  name: nginx-kusc00401
spec:
  nodeSelector:
    disk: spinning
  containers:
  - image: nginx
    name: nginx-kusc00401

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-kusc00402
  name: nginx-kusc00402
spec:
  nodeSelector:
    disktype: ssd
  containers:
  - image: nginx
    name: nginx-kusc00402
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-kusc00403
  name: nginx-kusc00403
spec:
  nodeSelector:
    gpu: "true"
  containers:
  - image: nginx
    name: nginx-kusc00403
