apiVersion: v1
kind: Pod
metadata:
  name: hungry-bear
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo "The app is running!" > /workdir/calm.txt && sleep 300
    image: busybox
    name: hungry-bear
    volumeMounts:
    - mountPath: /workdir
      name: cache-volume
  initContainers:
  - args:
    - /bin/sh
    - -c
    - touch /workdir/calm.txt
    image: busybox
    name: init-busybox
    volumeMounts:
    - mountPath: /workdir
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}