apiVersion: v1
data:
  connection_string: localhost:80
  external_url: cncf.io
kind: ConfigMap
metadata:
  name: web-config
  namespace: cka

---
apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: cka
spec:
  containers:
    - name: web-pod
      image: nginx:1.19.8-alpine
      ports:
      - containerPort: 80
      envFrom:
      - configMapRef:  
          name: web-config
