apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: busybox
    name: test
  command: ['/bin/sh', '-c', 'if [ -f /workdir/test.txt ]; then echo "the app is running!" > /workdir/test.txt && sleep 9999; fi']
    volumeMounts:
    - mountPath: /workdir
      name: cache-volume
  initContainers:
  - image: busybox
    name: init-test
    command: ['/bin/sh', '-c', 'touch /workdir/test.txt']
    volumeMounts:
    - mountPath: /workdir
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
