apiVersion: v1
data:
  key4: value3
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: another-config
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-configmap
  name: nginx-configmap
spec:
  containers:
  - image: nginx
    name: nginx-configmap
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-volume
      mountPath: /also/a/path
  volumes:
  - name: nginx-volume
    configMap:
      name: another-config