apiVersion: v1
kind: Pod
metadata:
  labels:
    run: front-end
  name: front-end
spec:
  containers:
    image: nginx
    name: front-end
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  selector:
    run: front-end
  ports:
    - protocol: TCP
      port: 80
  type: NodePort