apiVersion: v1
kind: Pod
metadata:
  namespace: ing-internal
  name: hi-pod
  labels:
    app: hi
spec:
  containers:
    - name: hi-container
      image: dbgurum/ingress:hi
      args:
        - "-text=Hi! kubernetes."
---
apiVersion: v1
kind: Service
metadata:
  name: hi-pod-service
  namespace: ing-internal
spec:
  selector:
    app: hi
  ports:
    - port: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pong
  namespace: ing-internal
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /hi
        pathType: Prefix
        backend:
          service:
            name: hi-pod-service
            port:
              number: 5678
