apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traffic
  namespace: cka00018
spec:
  podSelector:
    matchLabels:
      run: cka00018-newpod
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: web
    - podSelector:
        matchLabels:
          app: db
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: web
    - podSelector:
        matchLabels:
          app: db