apiVersion: v1
kind: Pod
metadata:
  name: mynode-pod
  labels: 
    app: node
spec:
  containers:
  - image: ${{ secrets.DOCKER_USERNAME }}/test:latest
    name: node-container
    ports:
    - containerPort: 8080
