apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: pod-viewer-sa
  namespace: api-access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: podviewer-role
  namespace: api-access
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: podviewer-rolebinding
  namespace: api-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podviewer-role
subjects:
- kind: ServiceAccount
  name: pod-viewer-sa
  namespace: api-access
