apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  nodeSelector:
    labels:
      gpu="true"
  containers:
  - image: nginx
    name: nginx-kusc00401
  - image: nginx
    name: nginx-kusc00402
  - image: nginx
    name: nginx-kusc00403
