apiVersion: v1
kind: Pod
metadata:
  labels:
    run: main
  name: main
spec:
  containers:
  - image: nginx
    name: main
    volumeMounts:
      - name: cache-volume
        mountPath: /workdir
  initContainers:
  - name: hungry-bear
    image: busybox
    command: ["/bin/sh", "-c", "touch /workdir/calm.txt"]
    volumeMounts:
      - name: cache-volume
        mountPath: /workdir
  volumes:
  - name: cache-volume
    emptyDir: {}
