apiVersion: v1
kind: LimitRange
metadata:
  name: billing-lr
  namespace: billing
spec:
  limits:
    - type: Pod
      max:
        cpu: "20m"
        memory: "800Mi"
      min:
        cpu: "10m"
        memory: "200m"

---

apiVersion: v1
kind: LimitRange
metadata:
  name: commerce-lr
  namespace: commerce
spec:
  limits:
    - type: Pod
      max:
        cpu: "35m"
        memory: 400Mi
      min:
        cpu: "10m"
        memory: 200Mi
        