apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-limit1
  name: pod-limit1
  namespace: dev-ns
spec:
  containers:
  - image: nginx
    name: pod-limit1
    resources:
      requests:
        cpu: "20m"
        memory: "100Mi"
      limits:
        cpu: "20m"
        memory: "200Mi"
