apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dev
  name: sales-dev
  namespace: dev
spec:
  containers:
  - args:
    - sales-dev
    image: ohhong/goapp:1.0
    name: sales-dev
    ports:
    - containerPort: 9000
