apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sales-prod
  name: sales-prod
  namespace: prod
spec:
  containers:
  - args:
    - sales-prod
    image: ohhong/goapp:1.0
    name: sales-prod
    ports:
    - containerPort: 9000
