apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dev
  name: shipping-dev
  namespace: dev
spec:
  containers:
  - args:
    - shipping-dev
    image: ohhong/myweb:1.0
    name: shipping-dev
    ports:
    - containerPort: 80